// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllConfig():Promise<main.Config>;

export function GetConfigInfo():Promise<Record<string, string>>;

export function GetHomePage():Promise<string>;

export function GetProxyServer():Promise<string>;

export function GetUserData():Promise<string>;

export function GetWebViewConfig():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function NavigateToHome():Promise<void>;

export function SetHomePage(arg1:string):Promise<void>;

export function SetProxyServer(arg1:string):Promise<void>;

export function SetUserData(arg1:string):Promise<void>;
